#!/bin/bash

# Derived from James Swaro's test, April 25, 2012

SENDER_PORT=4555
RECEIVER_PORT=4556

ACS=""
if [[ $BP_VERSION == "bpv6" ]] ; then
    echo "Looking for acsadmin"
    if [ $? -eq 0 ] ; then
        ACS="found"
    else
        ACS="missing"
    fi
fi

./cleanup

echo "Starting ION..."
export ION_NODE_LIST_DIR=$PWD

# Set up node 1
cd 1.ipn.udp/
if [[ $ACS == "found" ]] ; then
	./ionstart-acs
else
	./ionstart
fi
../../../system_up -i "p 30" -b "p 30"

if [ $? -ne 2 ]; then
    echo "Node 1 not started: Aborting Test"
    exit 1
fi

# Set up node 2
cd ../2.ipn.udp/
if [[ $ACS == "found" ]] ; then
	./ionstart-acs
else
	./ionstart
fi
../../../system_up -i "p 30" -b "p 30"

if [ $? -ne 2 ]; then
    echo "Node 2 not started: Aborting Test"
    exit 1
fi
echo "ION Nodes started successfully..."

# Start file receiver on node 2.
cd ../2.ipn.udp/
echo "Starting bprecvfile..."
bprecvfile ipn:2.1 &
sleep 10


# Send one file from node 1 to node 2.
cd ../1.ipn.udp/
echo "Sending file from node 1 to node 2..."
bpsendfile ipn:1.1 ipn:2.1 testfile

sleep 5

# Verify that this file arrived.
cd ../2.ipn.udp
COUNT=`ls -l testfile1 | egrep 117700 | wc -l`

if [[ $COUNT -eq 1 ]]; then
    RETVAL=0
else
    RETVAL=1
fi

# Shut down ION processes.
echo "Stopping ION..."
cd ../1.ipn.udp
./ionstop &
cd ../2.ipn.udp
./ionstop &

# Give nodes time to shut down, then clean up.
sleep 5
killm

if [[ $RETVAL -eq 0 ]]; then
    echo "UDP IPv6 test succeeded"
else
    echo "UDP IPv6 test failed"
fi

exit $RETVAL
